# Generated by Django 3.2.4 on 2021-06-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('Gender_Choice', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
