# Generated by Django 3.2.4 on 2021-06-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210622_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentc',
            new_name='Student',
        ),
    ]
