# Generated by Django 3.2.4 on 2021-06-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_studentc_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender_Choice',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='FEMALE', max_length=10, null=True),
        ),
    ]
