# Generated by Django 3.2.4 on 2021-06-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_studentc_student'),
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student'),
        ),
    ]
